#!/bin/bash
# shell script for easier project debugging

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

build () { 
	cmake -B build && cmake --build build; 
}
run () { 
	./build/reader $@; 
}
clean () {
	# /
	rm Makefile
	rm -r "$SCRIPT_DIR/build/"
	rm "$SCRIPT_DIR/CMakeCache.txt"
	rm "$SCRIPT_DIR/cmake_install.cmake"
	rm -r "$SCRIPT_DIR/CMakeFiles"
	# scripts/
	rm "$SCRIPT_DIR/reader/Makefile"
	rm "$SCRIPT_DIR/reader/cmake_install.cmake"
	rm -r "$SCRIPT_DIR/reader/CMakeFiles"

}

if [[ -z $1 ]]; then 
	echo "ERROR: no command line argument specified"
	exit 0
fi

# generate compile_commands.json
if [[ $1 == "cc" ]]; then 
	cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ./
	exit 0
fi
# delete files generated by cmake
if [[ $1 == "clear" || $1 == "clean" ]]; then 
	clean
	exit 0
fi
# build
if [[ $1 == "build" ]]; then 
	build
	exit 0
fi
# run 
if [[ $1 == "run" ]]; then 
	run ${@:2}
	exit 0
fi

build && run $@
